default_platform(:android)

platform :android do

    desc 'For develop build android test'
    lane :develop do
        gradle(
            project_dir: 'android/'
            task: 'assemble',
            build_type: 'Release',
            properties: {
                'dart-defines' => Base64.encode64('FLAVOR=prod')
            }
          )
    end

    desc 'For develop build android staging'
    lane :staging do |options|
        gradle(
            project_dir: 'android/'
            task: 'assemble',
            build_type: 'Release',
            properties: {
                'dart-defines' => Base64.encode64('FLAVOR=prod')
            }
          )

        firebase_app_distribution(
            app: '1:48062921415:android:9a92e85e8aebb106209ce2',
            firebase_cli_token: '1//0eCM_U17MwbEoCgYIARAAGA4SNwF-L9Ir4NL5CAjRDFdWmpk6v_e9s57QbwzTvcnhb7Z4gsp7edIYF-M95ryTts3JEpjW2KqAyRg',
            testers: 'nguyendangquanghbt12b7@gmail.com',
            android_artifact_path: '../build/app/outputs/flutter-apk/app-release.apk'
        )
    end

    desc 'For production build android'
    lane :production do
        gradle(
            project_dir: 'android/'
            task: 'assemble',
            build_type: 'Realse',
            properties: {
                'dart-defines' => Base64.encode64('FLAVOR=prod')
            }
        )
    end
end
